#!/bin/sh

# Placement daemon script that verifies service status, used for healthcheck and deploy. #placement#deploy#idoc

fail() { echo "BAD $@"; exit 0; }
ok() { echo "OK $@"; exit 0; }

# EDITME

responsews=$(curl -Lsf 'http://localhost:4001/socket.io/?EIO=2&transport=polling' -w '%{http_code}' -o /dev/null) || fail "unable to curl websocket"
response=$(curl -Lsf 'http://localhost:80' -w '%{http_code}' -o /dev/null) || fail "unable to curl app page"

if [ "$responsews" = "200" ] && [ "$response" = "200" ]; then
    ok "$response:$responsews"
else
    fail "$response:$responsews"
fi